- id: twemproxy
  type: puppet
  groups: [primary-controller, controller, compute, ironic-compute]
  required_for: [deploy_end, memcached]
  requires: [openstack-haproxy]
  parameters:
    puppet_manifest: "puppet/manifests/twemproxy.pp"
    puppet_modules: "puppet/modules"
    timeout: 3600
