- id: hiera_override
  type: puppet
  groups: [primary-controller, controller, compute, ironic-compute]
  required_for: [globals, deploy_end]
  requires: [hiera]
  parameters:
    puppet_manifest: "puppet/manifests/hiera_override.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: twemproxy
  type: puppet
  groups: [primary-controller, controller, compute, ironic-compute]
  required_for: [deploy_end, memcached]
  requires: [openstack-haproxy]
  parameters:
    puppet_manifest: "puppet/manifests/twemproxy.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600
