#!/bin/bash
set -eux

ROOT="$(dirname `readlink -f $0`)"
MODULES="${ROOT}"/deployment_scripts/puppet/modules
rm -rf "${MODULES}"
mkdir -p "${MODULES}"

git clone -b 0.1.0 --depth 1 https://github.com/sorrowless/puppet-twemproxy.git "${MODULES}/"twemproxy
